// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: somestub.proto

package somestub

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_somestub_proto protoreflect.FileDescriptor

const file_somestub_proto_rawDesc = "" +
	"\n" +
	"\x0esomestub.proto\x12\bsomestub\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto2\xda\x02\n" +
	"\bSomeStub\x12l\n" +
	"\x0fSelectSomething\x12\x1c.google.protobuf.StringValue\x1a\x1c.google.protobuf.StringValue\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/something/select\x12o\n" +
	"\x0fCreateSomething\x12\x1c.google.protobuf.StringValue\x1a\x1c.google.protobuf.StringValue\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/something/create\x12o\n" +
	"\x0fUpdateSomething\x12\x1c.google.protobuf.StringValue\x1a\x1c.google.protobuf.StringValue\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/something/updateB:Z8github.com/yylego/kratos-auth/internal/somestub;somestubb\x06proto3"

var file_somestub_proto_goTypes = []any{
	(*wrapperspb.StringValue)(nil), // 0: google.protobuf.StringValue
}
var file_somestub_proto_depIdxs = []int32{
	0, // 0: somestub.SomeStub.SelectSomething:input_type -> google.protobuf.StringValue
	0, // 1: somestub.SomeStub.CreateSomething:input_type -> google.protobuf.StringValue
	0, // 2: somestub.SomeStub.UpdateSomething:input_type -> google.protobuf.StringValue
	0, // 3: somestub.SomeStub.SelectSomething:output_type -> google.protobuf.StringValue
	0, // 4: somestub.SomeStub.CreateSomething:output_type -> google.protobuf.StringValue
	0, // 5: somestub.SomeStub.UpdateSomething:output_type -> google.protobuf.StringValue
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_somestub_proto_init() }
func file_somestub_proto_init() {
	if File_somestub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_somestub_proto_rawDesc), len(file_somestub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_somestub_proto_goTypes,
		DependencyIndexes: file_somestub_proto_depIdxs,
	}.Build()
	File_somestub_proto = out.File
	file_somestub_proto_goTypes = nil
	file_somestub_proto_depIdxs = nil
}
